# Getting started
## Installing R and R Studio {#installation}
- Before we can start the first analysis, we have to install "R" and "RStudio".
- "R" is a programming language used for statistical computing while "RStudio" provides a graphical user interface.
- "R" may be used without "RStudio", but "RStudio" may not be used without "R". Both, "R" and "RStudio" are free of charge and there are no licencse fees.

### Download and Install R
#### Windows

1. Open [https://cran.r-project.org/bin/windows/base/](https://cran.r-project.org/bin/windows/base/) and press the link "Download R..."
1. Run the downloaded installer file and follow the installation wizard

The wizard will install R into your "Program Files" folders and add a shortcut in your Start menu. Note that you will need to have all necessary administration rights to install new software on your machine.

#### Mac OSX
1. Open [https://cran.r-project.org/bin/macosx/](https://cran.r-project.org/bin/macosx/) and download the latest *.pkg file
1. Run the downloaded installer file and follow the installation wizard

The installer allows you to customize your installation. However the default values will be suitable for most users.

#### Linux
R is part of many Linux distributions, therefore you should check with your Linux package management system if it's already installed.

The CRAN website provides files to build R from source on Debian, Redhat, SUSE, and Ubuntu systems under the link “Download R for Linux”

- Open [https://cran.r-project.org/bin/linux/](https://cran.r-project.org/bin/linux/) and then follow the directory trail to the version of Linux you wish to install R on top of

The exact installation procedure will vary depending on your Linux operating system. CRAN supports the process by grouping each set of source files with documentation or README files that explain how to install on your system.

### Download and Install RStudio
R Studio is a development environment for R.

1. Open [https://rstudio.com/products/rstudio/download/](https://rstudio.com/products/rstudio/download/) and download "RStudio Desktop Open Source"
1. Follow the on-screen instructions
1. Once you have installed R Studio, you can run it like any other application via 

### Open RStudio
Now that you have both R and RStudio on your computer, you can begin using R by opening the RStudio program. Open RStudio just as you would any program, by clicking on its icon or by typing “RStudio” at the Windows Run prompt.

## Create your first R Script
blabla

## Whats next?
blabla
