--- 
title: "Energy Data Analysis with R"
author: "Reto Marek"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: hslu-ige-laes/edar
description: "Introduction into energy data analysis and visualization with R."

---

# Preface {#preface}

This book gives you an overview of the statistical software R and its ability to analyze and visualize time series in the context of building energy and comfort.

It is aimed at R beginners as well as exerienced R users and is strongly inspired by the <a href="https://r-graphics.org/" target="_blank">R Graphics Cookbook</a> and <a href="https://smogdr.github.io/edar_coursebook/" target="_blank">Engineering Data Analysis in R</a>. The aim of this book is to provide additional specific recipes for energy and comfort related tasks and to make your entry into R smooth and easy. 

## Content
The book is structured in the following main parts:

* R Basics

* Data Visualizations

The part "R Basics" covers general data analysis tasks like data loading, wrangling and aggregation. Mostly this part deals with number juggling and table viewing. An "R-beginner" receives as well information about the installation of the program environment and gets a quick and practical introduction.

> "Numerical quantities focus on expected values, graphical summaries on unexpected values." - John W. Tukey

Such so called "graphical summaries" are covered in the part "Data Visualizations" which brings the calculated numbers to life. Visualizations are good to identify patterns, changes over time, unusual readings, and relationships between variables. The presented code makes the creation of common and useful plots for energy and comfort data fast and easy.
The recipes in this part will show you how to complete certain specific tasks. Examples are shown so that you can understand the basic principle and reproduce the analysis or visualization with your own data. Simply copy the code into your R-script, replace the sample data files with your own and execute the code.

## Why R and RStudio?
In a study commissioned by the Swiss Federal Office of Energy, experts from the field were asked how and where they perform energy analyses and create visualizations. The result was that many people today either need Excel or use a building monitoring software to execute analysis and create visualizations.

Excel users are pushing the program to its limits with the ever-increasing data sets. Also the interactive ability of the graphics there is limited. The change to an environment like "R" seems to be difficult for many. In the market there are numerous books which make the change to "R" for other disciplines easier. However, experts from the energy and building services engineering industry lack a corresponding work. The present book is intended to close this gap.

The freely available programming language "R" and its graphical user interface "RStudio" offer many more possibilities for data analysis and data visualization.

## Further Reading
A really good source is <a href="http://r4ds.had.co.nz" target="_blank">R for Data Science</a> by Garrett Grolemund and Hadley Wickham. The entire book is freely available online through the same format of this book. 

There are a number of recommendable free online books available, including:

- <a href="https://r-graphics.org/" target="_blank">R Graphics Cookbook</a>
- <a href="https://rafalab.github.io/dsbook/" target="_blank">Introduction to Data Science - Data Analysis and Prediction Algorithms with R</a>
- <a href="https://rstudio-education.github.io/hopr/" target="_blank">Hands-On Programming with R</a>
- <a href="https://smogdr.github.io/edar_coursebook/" target="_blank">Engineering Data Analysis in R</a>
- <a href="https://otexts.com/fpp2/" target="_blank">Forecasting: Principles and Practice</a>
- <a href="https://afit-r.github.io/" target="_blank">AFIT Data Science Lab R Programming Guide</a>

## Acknowledgements
The author would like to express his sincere thank to the Swiss Federal Office of Energy, as the launch of this book was part of a project of the research program "Buildings and Cities 2018".

This book was developed using Yihui Xie's <a href="https://bookdown.org" target="_blank">bookdown</a> framework. The book is built  using code that combines R code, data, and text to create a book for which R code and examples can be re-executed every time the book is re-built.

The online book is hosted using GitHub's free <a href="https://pages.github.com" target="_blank">GitHub Pages</a>. All material for this book is available and can be explored at the book's <a href="https://github.com/hslu-ige-laes/edar" target="_blank">GitHub repository</a>.

