# (PART) R Basics {-}

# Introduction to R Basics

The following chapters of the part "R-Basics" is a short overview of the fundamental principles for understanding the code presented in the recipes in part "Data Visualizations".  It focuses on practical examples of how data can be loaded, transformed and analyzed.

It is not the goal of this book to fully introduce beginners to the programming language "R" and the environment in general. There are many really good sources where you can familiarize yourself with "R" if needed.

Two sources are recommended to facilitate the introduction to "R" and to learn the relevant basics. Choose one that suits you and go through the recommended chapter:

- [https://rafalab.github.io/dsbook/r-basics.html](Introduction to Data Science - Chapter 2 "R Basics"){target="_blank"}
- [https://smogdr.github.io/edar_coursebook/rprog1.html](Engineering Data Analysis in R - Chapter 2 "The R Programming Environment"){target="_blank"}

Throughout the book, reference is made to these two continuative sources and you only need to read the one that appeals to you more. In the referenced chapters, these cover similar content.
